import { useEffect, useState } from "react";
import { Link, useLocation, useNavigate, useParams } from "react-router-dom";
import { AlertCircle, ArrowLeft, ArrowRight, BriefcaseBusiness, FileText, Filter, MapPin, Search, ShieldCheck } from "lucide-react";
import { getCitizenCase, getCitizenLawyer, searchCitizenLawyers } from "../../services/citizenLawyerService";

const STATES = ["", "Andhra Pradesh", "Assam", "Bihar", "Delhi", "Gujarat", "Haryana", "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Odisha", "Punjab", "Rajasthan", "Tamil Nadu", "Telangana", "Uttar Pradesh", "Uttarakhand", "West Bengal", "Other"];
const TYPES = ["", "Criminal", "Civil", "Constitutional", "Commercial", "Family", "Property", "Labour", "Other"];
const STATUSES = ["", "Pending", "Disposed", "Admitted", "Hearing"];

const Shell = ({ children }) => <div className="space-y-6">{children}<p className="text-xs text-gray-400">Source: eCourtsIndia · Information is derived from available court data and is not an endorsement or recommendation.</p></div>;
const ErrorBox = ({ text }) => text ? <div className="flex gap-2 bg-red-50 border border-red-200 text-red-700 rounded-xl px-4 py-3 text-sm"><AlertCircle size={16} />{text}</div> : null;
const Avatar = ({ name }) => <div className="w-11 h-11 rounded-xl bg-gold-100 text-navy-700 flex items-center justify-center font-bold shrink-0">{(name || "Advocate").split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase()}</div>;
const Loading = () => <div className="space-y-3">{[1, 2, 3].map((item) => <div className="card p-4 animate-pulse flex gap-3" key={item}><div className="w-11 h-11 bg-gray-200 rounded-xl" /><div className="flex-1"><div className="h-4 bg-gray-200 rounded w-2/3 mb-2" /><div className="h-3 bg-gray-100 rounded w-1/2" /></div></div>)}</div>;
function Header() { return <section className="bg-navy-600 rounded-3xl p-7 text-white"><p className="text-navy-300 text-xs font-semibold uppercase tracking-widest flex gap-2"><BriefcaseBusiness size={15} /> Citizen Legal Assistance</p><h1 className="text-2xl font-bold mt-2">Find a Lawyer</h1><p className="text-navy-200 text-sm mt-1">Search lawyers associated with Indian court cases.</p></section>; }
function Filters({ filters, onChange }) { const set = (key, value) => onChange({ ...filters, [key]: value }); return <aside className="card p-4 space-y-3"><div className="font-semibold text-navy-700 flex gap-2"><Filter size={16} />Filters</div><label className="text-xs font-semibold text-gray-600 block">State<select className="input-field mt-1 w-full text-sm" value={filters.state} onChange={(e) => set("state", e.target.value)}>{STATES.map((item) => <option key={item} value={item}>{item || "All states"}</option>)}</select></label><label className="text-xs font-semibold text-gray-600 block">Court<input className="input-field mt-1 w-full text-sm" value={filters.court} onChange={(e) => set("court", e.target.value)} placeholder="Any court" /></label><label className="text-xs font-semibold text-gray-600 block">Case Type<select className="input-field mt-1 w-full text-sm" value={filters.case_type} onChange={(e) => set("case_type", e.target.value)}>{TYPES.map((item) => <option key={item} value={item}>{item || "All case types"}</option>)}</select></label><label className="text-xs font-semibold text-gray-600 block">Case Status<select className="input-field mt-1 w-full text-sm" value={filters.case_status} onChange={(e) => set("case_status", e.target.value)}>{STATUSES.map((item) => <option key={item} value={item}>{item || "All statuses"}</option>)}</select></label><label className="text-xs font-semibold text-gray-600 block">Sort<select className="input-field mt-1 w-full text-sm" value={filters.sort} onChange={(e) => set("sort", e.target.value)}><option value="relevant">Most Relevant</option><option value="related">Most Related Cases</option><option value="recent">Recent Cases</option><option value="name">Name A-Z</option></select></label></aside>; }
function Card({ lawyer, returnTo }) { const go = useNavigate(); return <article className="card p-4 flex flex-col sm:flex-row sm:items-center gap-3"><Avatar name={lawyer.name} /><div className="flex-1 min-w-0"><h3 className="font-bold text-navy-700 truncate">{lawyer.name}</h3><p className="text-sm text-gray-500 mt-1">{lawyer.courts?.[0] || "Court unavailable from records"}</p><p className="text-xs text-gray-400 mt-1 flex gap-1"><MapPin size={12} />{lawyer.locations?.join(", ") || "Location unavailable"}</p></div><p className="text-sm text-gray-600 shrink-0"><b>{lawyer.relatedCaseCount || 0}</b> related cases</p><button type="button" className="btn-outline px-4 py-2 rounded-xl text-sm" onClick={() => go(`/find-lawyer/${encodeURIComponent(lawyer.id)}`, { state: { returnTo } })}>View Profile <ArrowRight size={14} /></button></article>; }
function Pages({ meta, load }) { const last = Math.max(1, Math.ceil((meta.total || 0) / (meta.pageSize || 10))); if (last < 2) return null; const pages = [...new Set([1, meta.page - 1, meta.page, meta.page + 1, last].filter((item) => item > 0 && item <= last))].sort((a, b) => a - b); return <nav className="flex flex-wrap justify-center gap-1" aria-label="Pagination"><button className="btn-outline px-3 py-2 rounded-lg text-sm disabled:opacity-40" disabled={meta.page <= 1} onClick={() => load(meta.page - 1)}>Previous</button>{pages.map((page, index) => <span key={page}>{index > 0 && page - pages[index - 1] > 1 ? <span className="px-2 text-gray-400">...</span> : null}<button className={`px-3 py-2 rounded-lg text-sm ${page === meta.page ? "bg-navy-600 text-white" : "btn-outline"}`} onClick={() => load(page)} aria-current={page === meta.page ? "page" : undefined}>{page}</button></span>)}<button className="btn-outline px-3 py-2 rounded-lg text-sm disabled:opacity-40" disabled={!meta.hasNextPage && meta.page >= last} onClick={() => load(meta.page + 1)}>Next</button></nav>; }

export default function FindLawyerPage() {
  const [form, setForm] = useState({ legal_issue: "", advocate_name: "", state: "", district: "", practice_area: "" });
  const [filters, setFilters] = useState({ state: "", court: "", case_type: "", case_status: "", sort: "relevant" });
  const [results, setResults] = useState([]); const [meta, setMeta] = useState({ page: 1, pageSize: 10, total: 0, hasNextPage: false }); const [searched, setSearched] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const location = useLocation();
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const search = async (page = 1) => { setLoading(true); setError(""); setResults([]); try { const response = await searchCitizenLawyers({ ...form, page, page_size: 10 }); setResults(response.data.results || []); setMeta(response.data); setSearched(true); } catch (e) { setError(e.response?.data?.detail || "Unable to load lawyer information right now. Please try again."); setSearched(true); } finally { setLoading(false); } };
  const shown = results.filter((lawyer) => (!filters.state || lawyer.state === filters.state) && (!filters.court || lawyer.courts?.some((court) => court.toLowerCase().includes(filters.court.toLowerCase()))) && (!filters.case_type || lawyer.cases?.some((item) => item.caseType?.toLowerCase().includes(filters.case_type.toLowerCase()))) && (!filters.case_status || lawyer.cases?.some((item) => item.status?.toLowerCase().includes(filters.case_status.toLowerCase()))));
  const returnTo = `${location.pathname}${location.search}`;
  return <Shell><Header /><div className="text-xs text-gray-500"><Link to="/dashboard">Home</Link> / Find a Lawyer</div><form className="card p-4" onSubmit={(e) => { e.preventDefault(); search(1); }}><div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search size={17} className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" /><input className="input-field pl-11 py-3 text-base" value={form.legal_issue} onChange={(e) => update("legal_issue", e.target.value)} placeholder="Search by lawyer name or legal issue..." /></div><button className="btn-primary px-6 py-3 rounded-xl" disabled={loading}>{loading ? "Searching..." : "Search"}</button></div><p className="text-xs text-gray-400 mt-2">Search by lawyer name or legal issue.</p></form><ErrorBox text={error} />{loading && <Loading />}{!loading && !searched && <div className="card p-10 text-center"><ShieldCheck size={32} className="mx-auto text-emerald-500 mb-3" /><h2 className="font-bold text-navy-700">Find the right legal professional</h2><p className="text-sm text-gray-500">Search lawyers using their name or a legal issue.</p></div>}{!loading && searched && !error && <div className="grid gap-5 lg:grid-cols-[220px_1fr]"><div><Filters filters={filters} onChange={(next) => { setFilters(next); search(1); }} /></div><section className="space-y-3"><div><h2 className="text-lg font-bold text-navy-700">Lawyers matching your search</h2><p className="text-sm text-gray-500">Showing {shown.length} of {meta.total || shown.length} lawyers found in related court records.</p></div>{shown.length ? shown.map((lawyer) => <Card key={lawyer.id} lawyer={lawyer} returnTo={returnTo} />) : <div className="card p-8 text-center"><FileText size={30} className="mx-auto text-gray-400 mb-3" /><h2 className="font-bold text-navy-700">No lawyers found for the selected filters.</h2></div>}<Pages meta={meta} load={search} /></section></div>}</Shell>;
}

function CaseCard({ item, onOpen }) { return <button type="button" onClick={onOpen} className="card p-4 text-left w-full hover:border-gold-400"><h3 className="font-semibold text-navy-700">{item.title || [item.petitioners, item.respondents].filter(Boolean).join(" vs ") || "Case title unavailable"}</h3><p className="text-xs text-gray-500 mt-1">{item.court || "Court unavailable"} · {item.caseType || "Case type unavailable"}</p><p className="text-xs text-gray-500 mt-3">CNR: {item.cnr || "Not available"} · {item.status || "Status unavailable"}</p><span className="text-xs text-navy-600 mt-2 inline-block">View Case <ArrowRight size={13} className="inline" /></span></button>; }
export function LawyerProfilePage() { const { lawyerId } = useParams(); const location = useLocation(); const navigate = useNavigate(); const [lawyer, setLawyer] = useState(null); const [error, setError] = useState(""); useEffect(() => { getCitizenLawyer(lawyerId).then((response) => setLawyer(response.data)).catch((e) => setError(e.response?.data?.detail || "Unable to load lawyer information right now. Please try again.")); }, [lawyerId]); const back = () => location.state?.returnTo ? navigate(location.state.returnTo) : navigate("/find-lawyer"); if (error) return <Shell><ErrorBox text={error} /></Shell>; if (!lawyer) return <Shell><Loading /></Shell>; const contacts = [["Email", lawyer.email], ["Phone", lawyer.phone], ["WhatsApp", lawyer.whatsapp]].filter(([, value]) => value); return <Shell><button className="btn-outline px-3 py-2 rounded-lg text-sm" onClick={back}><ArrowLeft size={14} className="inline" /> Back to Search Results</button><div className="text-xs text-gray-500"><Link to="/dashboard">Home</Link> / <Link to={location.state?.returnTo || "/find-lawyer"}>Find a Lawyer</Link> / {lawyer.name}</div><section className="card p-5"><div className="flex items-start gap-4"><Avatar name={lawyer.name} /><div><h1 className="text-2xl font-bold text-navy-700">{lawyer.name}</h1><p className="text-sm text-gray-500 mt-1">{lawyer.locations?.join(", ") || "Location unavailable from court records"}</p></div></div><div className="grid gap-3 sm:grid-cols-3 mt-5"><p><b>{lawyer.relatedCaseCount || 0}</b><span className="block text-xs text-gray-500">Related cases</span></p><p><b>{lawyer.courtActivity?.pendingCases || 0}</b><span className="block text-xs text-gray-500">Pending</span></p><p><b>{lawyer.courtActivity?.disposedCases || 0}</b><span className="block text-xs text-gray-500">Disposed</span></p></div><div className="mt-5"><h2 className="font-semibold text-navy-700">Contact Information</h2>{contacts.length ? contacts.map(([label, value]) => <p className="text-sm text-gray-600 mt-2" key={label}>{label}: {value}</p>) : <p className="text-sm text-gray-500 mt-2">Contact information is not available from connected court records.</p>}</div><div className="flex flex-wrap gap-2 mt-5">{lawyer.courts?.map((court) => <span key={court} className="badge bg-navy-50 text-navy-700">{court}</span>)}</div></section><section className="space-y-3"><h2 className="text-lg font-bold text-navy-700">Cases represented by {lawyer.name}</h2>{lawyer.cases?.map((item, index) => <CaseCard key={`${item.cnr || "case"}-${index}`} item={item} onOpen={() => navigate(`/find-lawyer/case/${encodeURIComponent(item.cnr)}`, { state: { lawyerName: lawyer.name, profilePath: location.pathname, returnTo: location.state?.returnTo } })} />)}</section></Shell>; }
export function LawyerCaseDetailPage() { const { cnr } = useParams(); const location = useLocation(); const navigate = useNavigate(); const [item, setItem] = useState(null); const [error, setError] = useState(""); useEffect(() => { getCitizenCase(cnr).then((response) => setItem(response.data)).catch((e) => setError(e.response?.data?.detail || "Unable to load case information right now. Please try again.")); }, [cnr]); const back = () => location.state?.profilePath ? navigate(location.state.profilePath, { state: { returnTo: location.state.returnTo } }) : navigate("/find-lawyer"); if (error) return <Shell><ErrorBox text={error} /></Shell>; if (!item) return <Shell><Loading /></Shell>; return <Shell><button className="btn-outline px-3 py-2 rounded-lg text-sm" onClick={back}><ArrowLeft size={14} className="inline" /> Back to {location.state?.lawyerName || "lawyer profile"}</button><div className="text-xs text-gray-500"><Link to="/dashboard">Home</Link> / <Link to={location.state?.returnTo || "/find-lawyer"}>Find a Lawyer</Link> / {location.state?.lawyerName ? <Link to={location.state.profilePath}>{location.state.lawyerName}</Link> : null} / Case Details</div><section className="card p-5"><h1 className="text-2xl font-bold text-navy-700">{item.title || [item.petitioners, item.respondents].filter(Boolean).join(" vs ") || "Case details"}</h1><div className="grid gap-3 mt-5 sm:grid-cols-2">{[["Court", item.court], ["Case type", item.caseType], ["Case number", item.caseNumber], ["Filing number", item.filingNumber], ["CNR", item.cnr], ["Status", item.status], ["Category", item.category], ["Filing date", item.filingDate], ["Decision date", item.decisionDate], ["Next hearing", item.nextHearingDate], ["Acts / Sections", item.acts]].filter(([, value]) => value).map(([label, value]) => <div key={label}><p className="text-xs uppercase tracking-wide text-gray-400">{label}</p><p className="text-sm text-navy-700 mt-1">{String(value)}</p></div>)}</div></section></Shell>; }
