import { useState } from "react";
import { FileText, Plus, Trash2, Sparkles, Download, Pencil, RotateCcw, AlertCircle, Scale } from "lucide-react";
import { downloadLegalDraftPdf, generateLegalDraft } from "../../services/legalDraftService";

const TYPES = ["Legal Notice", "Complaint", "Petition", "Application", "Representation", "Reply / Response", "Affidavit Draft", "Consumer Complaint", "Civil Application", "Criminal Complaint", "Other Legal Draft"];
const emptyParty = () => ({ name: "", role: "Applicant / Petitioner", address: "", contact: "" });
const initial = { document_type: "Legal Notice", other_document_type: "", matter_title: "", jurisdiction: "", state: "", district: "", court: "", case_type: "", subject: "", case_status: "", incident_date: "", case_number: "", parties: [emptyParty()], facts: "", important_dates: "", events: "", documents_available: "", previous_notices: "", previous_proceedings: "", known_acts: "", known_sections: "", legal_provisions: "", judgments_citations: "", legal_research: "", relief_requested: "", additional_information: "" };

function Field({ label, children, optional = true }) { return <label className="block text-sm font-semibold text-navy-700">{label}{optional && <span className="font-normal text-gray-400"> (optional)</span>}{children}</label>; }
function Area({ value, onChange, placeholder, rows = 4 }) { return <textarea className="input-field mt-1 w-full min-h-24" rows={rows} value={value} onChange={onChange} placeholder={placeholder} />; }

function PaperPreview({ draft, editing, onChange, downloading, onDownload }) {
  if (!draft) return <div className="hidden lg:flex sticky top-6 min-h-[520px] card items-center justify-center p-8 text-center text-gray-400"><div><FileText size={34} className="mx-auto mb-3 text-gold-500" /><p className="font-semibold text-navy-700">Your legal draft will appear here</p><p className="mt-2 text-sm">Complete the guided workspace and generate a draft for review.</p></div></div>;
  const set = (key, value) => onChange({ ...draft, [key]: value });
  const setSection = (index, value) => onChange({ ...draft, sections: draft.sections.map((item, i) => i === index ? { ...item, content: value } : item) });
  return <div className="lg:sticky lg:top-6"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-semibold text-navy-700">Draft preview</p><div className="flex items-center gap-2"><span className="badge bg-gold-50 text-gold-700">AI-generated legal draft for review</span><button className="btn-primary rounded-lg px-3 py-2 text-xs" disabled={downloading} onClick={onDownload}><Download size={14}/>{downloading ? "Generating PDF…" : "Download PDF"}</button></div></div><article className="bg-white shadow-[0_8px_32px_rgba(20,36,58,.13)] border border-[#ded9ce] min-h-[720px] p-8 sm:p-12 text-[13px] text-slate-800 leading-6">
    <header className="text-center border-b border-gold-300 pb-5"><p className="text-[10px] tracking-[.15em] font-bold text-navy-700">NYAYAAI | LEGAL INTELLIGENCE PLATFORM</p><p className="text-[10px] mt-1 text-gray-500">AI-GENERATED LEGAL DRAFT FOR REVIEW</p><p className="font-bold mt-5">{editing ? <input className="text-center border-b w-full" value={draft.court_heading} onChange={e => set("court_heading", e.target.value)} /> : draft.court_heading}</p><h2 className="font-bold text-base mt-2">{editing ? <input className="text-center border-b w-full" value={draft.title} onChange={e => set("title", e.target.value)} /> : draft.title}</h2><p className="text-xs mt-1">{draft.document_type}</p></header>
    {draft.parties?.length > 0 && <section className="mt-6"><h3 className="font-bold">PARTIES</h3>{draft.parties.map((party, i) => <p key={i} className="mt-2">{[party.role, party.name, party.address, party.contact].filter(Boolean).join(" — ")}</p>)}</section>}
    {draft.sections.map((section, index) => <section className="mt-6" key={`${section.heading}-${index}`}><h3 className="font-bold uppercase">{index + 1}. {section.heading}</h3>{editing ? <Area value={section.content} onChange={e => setSection(index, e.target.value)} rows={5} /> : <p className="whitespace-pre-line text-justify mt-2">{section.content}</p>}</section>)}
    <section className="mt-6"><h3 className="font-bold">PRAYER / RELIEF</h3>{editing ? <Area value={draft.prayer} onChange={e => set("prayer", e.target.value)} /> : <p className="whitespace-pre-line text-justify mt-2">{draft.prayer}</p>}</section><section className="mt-6"><h3 className="font-bold">VERIFICATION</h3><p className="mt-2">{draft.verification}</p></section><div className="mt-8">{draft.signature_fields.map(field => <p key={field}>{field}</p>)}</div><footer className="mt-10 pt-3 border-t text-[10px] text-gray-500">{draft.disclaimer}</footer>
  </article></div>;
}

export default function LegalDraftGeneratorPage() {
  const [form, setForm] = useState(initial); const [draft, setDraft] = useState(null); const [editing, setEditing] = useState(false); const [loading, setLoading] = useState(false); const [downloading, setDownloading] = useState(false); const [error, setError] = useState(""); const [confirmRegenerate, setConfirmRegenerate] = useState(false);
  const update = (key, value) => setForm(current => ({ ...current, [key]: value }));
  const updateParty = (index, key, value) => setForm(current => ({ ...current, parties: current.parties.map((party, i) => i === index ? { ...party, [key]: value } : party) }));
  const generate = async () => { if (form.facts.trim().length < 20 || form.relief_requested.trim().length < 10) { setError("Please provide the facts of the matter and the relief or request sought."); return; } setLoading(true); setError(""); try { const response = await generateLegalDraft(form); setDraft(response.data.data); setEditing(false); setConfirmRegenerate(false); } catch (e) { setError(e.response?.data?.message || "Unable to generate the draft right now. Please review your information and try again."); } finally { setLoading(false); } };
  const pdf = async () => { setDownloading(true); setError(""); try { const response = await downloadLegalDraftPdf(draft); const url = URL.createObjectURL(new Blob([response.data], { type: "application/pdf" })); const filenamePart = (form.matter_title || draft.title || draft.document_type).replace(/[<>:"/\\|?*]+/g, "").replace(/\s+/g, "_").slice(0, 100) || "Legal_Draft"; const link = document.createElement("a"); link.href = url; link.download = `NyayaAI_Legal_Draft_${filenamePart}.pdf`; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); } catch { setError("Unable to generate the PDF. Please try again."); } finally { setDownloading(false); } };
  return <div className="space-y-6"><section className="nyaya-hero p-7 sm:p-9 text-white"><div className="flex gap-2 text-gold-300 text-[10px] font-bold tracking-[.18em] uppercase"><FileText size={15} /> NyayaAI Legal Drafting Workspace</div><h1 className="mt-3 text-3xl font-normal">AI Legal Draft Generator</h1><p className="mt-2 text-sm text-navy-100">Turn your legal information into a structured draft with NyayaAI.</p></section>
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(380px,.9fr)]"><div className="space-y-5"><div className="bg-amber-50 border border-amber-200 rounded-xl p-4 text-sm text-amber-900"><b>Drafting assistance only.</b> Your draft is prepared from the information you provide and should be reviewed by a qualified legal professional before filing or formal use.</div>
      {error && <div className="flex gap-2 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><AlertCircle size={17} className="shrink-0" />{error}</div>}
      <section className="card p-5"><p className="section-label">Step 1</p><h2 className="text-xl font-bold text-navy-700">What type of legal draft do you need?</h2><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3">{TYPES.map(type => <button type="button" key={type} onClick={() => update("document_type", type)} className={`rounded-xl border p-3 text-left text-sm font-semibold ${form.document_type === type ? "border-gold-400 bg-gold-50 text-navy-700" : "border-gray-200 bg-white text-gray-600 hover:border-gold-300"}`}>{type}</button>)}</div>{form.document_type === "Other Legal Draft" && <input className="input-field mt-4" value={form.other_document_type} onChange={e => update("other_document_type", e.target.value)} placeholder="Describe the document you need" />}</section>
      <section className="card p-5"><p className="section-label">Step 2</p><h2 className="text-xl font-bold text-navy-700">Matter details</h2><div className="mt-4 grid gap-4 sm:grid-cols-2">{[["matter_title","Case / Matter Title"],["jurisdiction","Jurisdiction"],["state","State"],["district","City / District"],["court","Court / Authority"],["case_type","Case Type"],["subject","Subject / Legal Issue"],["case_status","Current Case Status"],["incident_date","Date of Incident / Relevant Date"],["case_number","Reference / Case Number"]].map(([key,label]) => <Field key={key} label={label}><input className="input-field mt-1" value={form[key]} onChange={e => update(key,e.target.value)} /></Field>)}</div></section>
      <section className="card p-5"><p className="section-label">Step 3</p><div className="flex justify-between gap-3"><h2 className="text-xl font-bold text-navy-700">Parties involved</h2><button type="button" className="btn-outline px-3 py-2 rounded-lg text-xs" onClick={() => update("parties", [...form.parties, emptyParty()])}><Plus size={14}/> Add party</button></div>{form.parties.map((party,index) => <div className="mt-4 rounded-xl border border-gray-200 p-4" key={index}><div className="mb-3 flex justify-between"><p className="font-semibold text-navy-700">Party {index + 1}</p>{form.parties.length > 1 && <button type="button" onClick={() => update("parties", form.parties.filter((_, i) => i !== index))} className="text-red-500"><Trash2 size={16}/></button>}</div><div className="grid gap-3 sm:grid-cols-2">{[["role","Role"],["name","Name"],["address","Address"],["contact","Contact information"]].map(([key,label]) => <Field key={key} label={label}><input className="input-field mt-1" value={party[key]} onChange={e => updateParty(index,key,e.target.value)} /></Field>)}</div></div>)}</section>
      <section className="card p-5"><p className="section-label">Step 4</p><h2 className="text-xl font-bold text-navy-700">Describe what happened</h2><p className="mt-1 text-sm text-gray-500">Explain the facts in your own words. Include important dates, events, communications, transactions, notices, and other relevant details.</p><Area value={form.facts} onChange={e => update("facts",e.target.value)} placeholder="Describe the facts and circumstances of your matter…" rows={8}/><div className="mt-4 grid gap-4 sm:grid-cols-2">{[["important_dates","Important dates"],["events","Key events"],["documents_available","Documents available"],["previous_notices","Previous notices"],["previous_proceedings","Previous proceedings"]].map(([key,label]) => <Field key={key} label={label}><Area value={form[key]} onChange={e => update(key,e.target.value)} placeholder={label} rows={3}/></Field>)}</div></section>
      <section className="card p-5"><p className="section-label">Step 5</p><h2 className="text-xl font-bold text-navy-700">Legal information</h2><p className="mt-1 text-sm text-gray-500">All fields are optional. User-provided provisions are never treated as verified automatically.</p><div className="mt-4 grid gap-4 sm:grid-cols-2">{[["known_acts","Known Acts"],["known_sections","Known Sections"],["legal_provisions","Legal provisions"],["judgments_citations","Relevant judgments / citations"],["legal_research","Legal research you already have"]].map(([key,label]) => <Field key={key} label={label}><Area value={form[key]} onChange={e => update(key,e.target.value)} placeholder={label} rows={3}/></Field>)}</div></section>
      <section className="card p-5"><p className="section-label">Step 6</p><h2 className="text-xl font-bold text-navy-700">What should the document request?</h2><Area value={form.relief_requested} onChange={e => update("relief_requested",e.target.value)} placeholder="Describe the action, relief, remedy, direction, or response you are seeking." rows={5}/><Field label="Additional information"><Area value={form.additional_information} onChange={e => update("additional_information",e.target.value)} placeholder="Supporting information, special instructions, or other relevant details" rows={4}/></Field></section>
      <button type="button" onClick={() => draft ? setConfirmRegenerate(true) : generate()} disabled={loading} className="btn-gold w-full rounded-xl py-3.5">{loading ? "NyayaAI is preparing your legal draft…" : <><Sparkles size={17}/> Generate Legal Draft</>}</button>{confirmRegenerate && <div className="card p-4 text-sm"><p>Your current draft will be replaced. Your edited content will not be retained.</p><div className="mt-3 flex gap-3"><button className="btn-primary rounded-lg px-4 py-2" onClick={generate}>Replace draft</button><button className="btn-outline rounded-lg px-4 py-2" onClick={() => setConfirmRegenerate(false)}>Keep current</button></div></div>}</div>
      <div className="space-y-4"><PaperPreview draft={draft} editing={editing} onChange={setDraft} downloading={downloading} onDownload={pdf}/>{draft && <><div className="flex flex-wrap gap-3"><button className="btn-outline rounded-xl px-4 py-2.5" onClick={() => setEditing(!editing)}><Pencil size={15}/>{editing ? "Finish editing" : "Edit Draft"}</button><button className="btn-outline rounded-xl px-4 py-2.5" onClick={() => setConfirmRegenerate(true)}><RotateCcw size={15}/>Regenerate Draft</button></div>{draft.potentially_relevant_provisions?.length > 0 && <section className="card p-4"><h2 className="font-bold text-navy-700">Potentially relevant legal sources</h2><p className="mt-1 text-xs text-gray-500">For professional verification; these are not asserted as confirmed legal provisions.</p>{draft.potentially_relevant_provisions.map((item,i) => <div className="mt-3 text-sm" key={i}><b>{item.label}</b><p className="text-gray-600">{item.summary}</p><p className="text-xs text-gray-400">Source: {item.source}</p></div>)}</section>}</>}</div></div></div>;
}
