import { useEffect, useState } from "react";
import { AlertCircle, ArrowDown, BookOpen, Brain, FileSearch, Gavel, GitBranch, Scale, Search } from "lucide-react";
import { analyzePrecedents, compareJudgments, getLegalReasoning, listJudgeJudgments, synthesizeCaseLaw } from "../../services/judgeService";

function Header({ icon: Icon, eyebrow, title, description }) {
  return <div className="bg-navy-600 rounded-3xl p-7 text-white"><div className="flex items-center gap-2 text-gold-400 text-xs font-semibold uppercase tracking-widest"><Icon size={15} />{eyebrow}</div><h1 className="text-2xl font-bold mt-2">{title}</h1><p className="text-navy-200 text-sm mt-1">{description}</p></div>;
}
function Notice({ error }) { return error ? <div className="flex gap-2 bg-red-50 text-red-700 border border-red-200 rounded-xl p-4 text-sm"><AlertCircle size={16} />{error}</div> : null; }
function Loader({ loading }) { return loading ? <div className="text-sm text-navy-600 animate-pulse">Generating judicial intelligence…</div> : null; }

function JudgmentPicker({ label, value, onChange }) {
  const [query, setQuery] = useState(""); const [items, setItems] = useState([]);
  useEffect(() => { const t = setTimeout(() => listJudgeJudgments({ query }).then(r => setItems(r.data.data)).catch(() => setItems([])), 300); return () => clearTimeout(t); }, [query]);
  return <div className="card p-5"><label className="block text-sm font-semibold text-navy-700 mb-2">{label}</label><div className="relative"><Search size={16} className="absolute top-3 left-3 text-gray-400" /><input className="input-field pl-9" value={query} placeholder="Search repository judgments" onChange={e => setQuery(e.target.value)} /></div><select className="input-field mt-3" value={value || ""} onChange={e => onChange(e.target.value)}><option value="">Select a judgment</option>{items.map(item => <option key={item.id} value={item.id}>{item.title} · {item.court || "Court unavailable"} · {item.year || ""}</option>)}</select></div>;
}

export function JudgeJudgmentComparisonPage() {
  const [a, setA] = useState(""); const [b, setB] = useState(""); const [result, setResult] = useState(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const compare = async () => { setLoading(true); setError(""); try { setResult((await compareJudgments(a, b)).data.data); } catch (e) { setError(e.response?.data?.message || e.response?.data?.detail || "Comparison failed."); } finally { setLoading(false); } };
  const rows = result ? [["Case Name", result.judgment_a.case_title, result.judgment_b.case_title], ["Court", result.judgment_a.court, result.judgment_b.court], ["Year", result.judgment_a.year, result.judgment_b.year], ["Judge Bench", result.judgment_a.bench, result.judgment_b.bench], ["Acts / Sections", result.comparison.statutes.common_statutes?.join(", ") || "—", result.comparison.statutes.only_in_judgment_b?.join(", ") || "—"]] : [];
  return <div className="space-y-6"><Header icon={Scale} eyebrow="Judicial intelligence" title="Judgment Comparison" description="Compare legal reasoning, issues and outcomes across two judgments." /><div className="grid md:grid-cols-2 gap-5"><JudgmentPicker label="Judgment A" value={a} onChange={setA} /><JudgmentPicker label="Judgment B" value={b} onChange={setB} /></div><button className="btn-primary px-6 py-3 rounded-xl disabled:opacity-50" disabled={!a || !b || loading} onClick={compare}>Compare Judgments</button><Loader loading={loading}/><Notice error={error}/>{result && <div className="space-y-5"><div className="card p-5"><p className="text-sm text-gray-500">Overall semantic similarity</p><p className="text-4xl font-bold text-gold-500">{result.overall_similarity}%</p></div><div className="card overflow-auto"><table className="w-full text-sm"><thead className="bg-navy-50 text-navy-700"><tr><th className="p-3 text-left">Field</th><th className="p-3 text-left">Judgment A</th><th className="p-3 text-left">Judgment B</th></tr></thead><tbody>{rows.map(row => <tr key={row[0]} className="border-t"><td className="p-3 font-semibold">{row[0]}</td><td className="p-3">{row[1] || "—"}</td><td className="p-3">{row[2] || "—"}</td></tr>)}</tbody></table></div>{[["Facts", result.comparison.facts], ["Legal Issues", result.comparison.legal_issues], ["Arguments", result.comparison.arguments], ["Reasoning", result.comparison.reasoning], ["Final Decision", result.comparison.outcome]].map(([title, data]) => <div key={title} className="card p-5"><h2 className="font-bold text-navy-700">{title}</h2><div className="grid md:grid-cols-2 gap-4 mt-3 text-sm"><p>{data.judgment_a || "No extraction available."}</p><p>{data.judgment_b || "No extraction available."}</p></div>{data.common_elements && <p className="text-xs text-gray-500 mt-3">Common elements: {data.common_elements.join(", ")}</p>}{data.relationship && <p className="text-xs text-gold-600 mt-3">{data.relationship}</p>}</div>)}</div>}</div>;
}

export function JudgePrecedentAnalysisPage() {
  const [issue, setIssue] = useState(""); const [result, setResult] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const run = async () => { setLoading(true); setError(""); try { setResult((await analyzePrecedents(issue)).data.data); } catch (e) { setError(e.response?.data?.detail || "Precedent analysis failed."); } finally { setLoading(false); } };
  return <div className="space-y-6"><Header icon={GitBranch} eyebrow="Judicial intelligence" title="Precedent Analysis" description="Retrieve, rank and explain authorities relevant to a legal issue." /><div className="card p-5 flex gap-3"><input className="input-field" value={issue} onChange={e => setIssue(e.target.value)} placeholder="e.g. Right to privacy under Article 21"/><button className="btn-primary px-5 rounded-xl" disabled={!issue || loading} onClick={run}>Analyze</button></div><Loader loading={loading}/><Notice error={error}/>{result && <><div className="grid gap-4">{result.precedents.map(p => <div className="card p-5" key={p.id}><div className="flex justify-between gap-4"><div><h2 className="font-bold text-navy-700">{p.title}</h2><p className="text-sm text-gray-500">{p.court} · {p.year} · {p.citation}</p></div><span className="badge bg-gold-50 text-gold-700">{p.relevance_score}% relevance</span></div><p className="text-sm text-navy-600 mt-3">{p.ratio}</p><div className="mt-3 text-xs font-semibold text-purple-700">{p.binding_strength} · {p.citation_relationship}</div></div>)}</div><div className="card p-5"><h2 className="font-bold text-navy-700">Citation Relationships</h2><p className="text-sm text-gray-600 mt-2">{result.citation_graph.edges.map(e => `${e.source} → ${e.label} → ${e.target}`).slice(0, 12).join(" · ") || "No citation relationship identified."}</p></div></>}</div>;
}

export function JudgeLegalReasoningPage() {
  const [id, setId] = useState(""); const [result, setResult] = useState(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const run = async () => { setLoading(true); setError(""); try { setResult((await getLegalReasoning(id)).data.data); } catch (e) { setError(e.response?.data?.detail || "Reasoning extraction failed."); } finally { setLoading(false); } };
  return <div className="space-y-6"><Header icon={Brain} eyebrow="Judicial intelligence" title="Legal Reasoning Extraction" description="Trace the reasoning path from facts through ratio decidendi and final decision." /><div className="flex gap-3"><JudgmentPicker label="Select judgment" value={id} onChange={setId}/><button className="btn-primary px-5 h-11 mt-10 rounded-xl" disabled={!id || loading} onClick={run}>Extract</button></div><Loader loading={loading}/><Notice error={error}/>{result && <div className="card p-6"><h2 className="font-bold text-navy-700 mb-5">{result.case.title}</h2>{result.flow.map((step, index) => <div key={step.stage}><div className="border border-navy-100 bg-navy-50 rounded-xl p-4"><p className="font-semibold text-navy-700">{step.stage}</p><p className="text-sm text-gray-600 mt-1 whitespace-pre-line">{step.content}</p></div>{index < result.flow.length - 1 && <ArrowDown className="mx-auto text-gold-500 my-2" />}</div>)}</div>}</div>;
}

export function JudgeCaseLawSynthesisPage() {
  const [topic, setTopic] = useState(""); const [result, setResult] = useState(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const run = async () => { setLoading(true); setError(""); try { setResult((await synthesizeCaseLaw(topic)).data.data); } catch (e) { setError(e.response?.data?.detail || "Synthesis failed."); } finally { setLoading(false); } };
  return <div className="space-y-6"><Header icon={BookOpen} eyebrow="Judicial intelligence" title="Case-law Synthesis" description="Build a topic-level view of the evolution, principles and current legal position." /><div className="card p-5 flex gap-3"><input className="input-field" value={topic} onChange={e => setTopic(e.target.value)} placeholder="e.g. Sexual harassment at workplace"/><button className="btn-primary px-5 rounded-xl" disabled={!topic || loading} onClick={run}>Synthesize</button></div><Loader loading={loading}/><Notice error={error}/>{result && <div className="grid gap-5"><div className="card p-5"><h2 className="font-bold text-navy-700">Evolution of Law</h2>{result.timeline.map(t => <div className="mt-4 flex gap-3" key={`${t.case}-${t.year}`}><div className="text-gold-600 font-bold">{t.year || "—"}</div><div><p className="font-semibold text-navy-700">{t.case}</p><p className="text-sm text-gray-600">{t.event}</p></div></div>)}</div><div className="card p-5"><h2 className="font-bold text-navy-700">Common Legal Principles</h2><ul className="list-disc ml-5 mt-3 text-sm text-gray-600 space-y-2">{result.common_legal_principles.map(p => <li key={p}>{p}</li>)}</ul></div><div className="card p-5"><h2 className="font-bold text-navy-700">Conflicting Views</h2><ul className="list-disc ml-5 mt-3 text-sm text-gray-600 space-y-2">{result.conflicting_views.map(p => <li key={p}>{p}</li>)}</ul></div><div className="bg-gold-50 border border-gold-200 rounded-2xl p-5"><h2 className="font-bold text-navy-700">Current Legal Position</h2><p className="text-sm text-navy-700 mt-2">{result.current_legal_position}</p></div></div>}</div>;
}
